[2016-09-04 20:25:38] ERROR [http-nio-8080-exec-4] UserDAOImpl.list(44) | org.hibernate.hql.internal.ast.QuerySyntaxException: User is not mapped [from User]
[2016-09-04 20:25:46] ERROR [http-nio-8080-exec-5] UserDAOImpl.insert(59) | Unknown entity: com.hiber.model.User
[2016-09-04 20:25:46] INFO [http-nio-8080-exec-5] UserController.addNew(60) | add new user -----> com.hiber.model.User@333cbdcd
[2016-09-04 20:25:46] ERROR [http-nio-8080-exec-6] UserDAOImpl.list(44) | org.hibernate.hql.internal.ast.QuerySyntaxException: User is not mapped [from User]
[2016-09-04 20:27:45] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Syntax error: Encountered "User" at line 1, column 14.
[2016-09-04 20:27:45] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@38635af0{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 20:28:03] ERROR [http-nio-8080-exec-3] UserDAOImpl.list(44) | org.hibernate.hql.internal.ast.QuerySyntaxException: User is not mapped [from User]
[2016-09-04 20:28:14] ERROR [http-nio-8080-exec-4] UserDAOImpl.insert(59) | Unknown entity: com.hiber.model.User
[2016-09-04 20:28:14] INFO [http-nio-8080-exec-4] UserController.addNew(60) | add new user -----> com.hiber.model.User@30f14f5f
[2016-09-04 20:28:14] ERROR [http-nio-8080-exec-5] UserDAOImpl.list(44) | org.hibernate.hql.internal.ast.QuerySyntaxException: User is not mapped [from User]
[2016-09-04 20:29:35] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 20:29:35] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@74f04401{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 20:30:55] INFO [main] ContextStartEventHandler.onApplicationEvent(47) | Context start application org.apache.tomcat.jdbc.pool.DataSource@d23aeae{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 20:31:30] ERROR [http-nio-8080-exec-4] UserDAOImpl.list(44) | org.hibernate.hql.internal.ast.QuerySyntaxException: User is not mapped [from User]
[2016-09-04 20:33:09] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'GROUPS' already exists in Schema 'SA'.
[2016-09-04 20:33:09] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@2f011329{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 20:33:58] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@54f9ca51{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 20:37:03] ERROR [http-nio-8080-exec-3] UserDAOImpl.list(44) | org.hibernate.hql.internal.ast.QuerySyntaxException: Users is not mapped [from Users]
[2016-09-04 20:37:41] ERROR [http-nio-8080-exec-4] UserDAOImpl.insert(59) | Unknown entity: com.hiber.model.User
[2016-09-04 20:37:41] INFO [http-nio-8080-exec-4] UserController.addNew(60) | add new user -----> com.hiber.model.User@360353cc
[2016-09-04 20:37:41] ERROR [http-nio-8080-exec-5] UserDAOImpl.list(44) | org.hibernate.hql.internal.ast.QuerySyntaxException: Users is not mapped [from Users]
[2016-09-04 20:39:54] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 20:39:54] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@3ecf2170{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 20:40:20] ERROR [http-nio-8080-exec-3] UserDAOImpl.list(44) | org.hibernate.hql.internal.ast.QuerySyntaxException: Users is not mapped [from Users]
[2016-09-04 20:40:28] ERROR [http-nio-8080-exec-4] UserDAOImpl.insert(59) | Unknown entity: com.hiber.model.User
[2016-09-04 20:40:28] INFO [http-nio-8080-exec-4] UserController.addNew(60) | add new user -----> com.hiber.model.User@40bd8ddb
[2016-09-04 20:40:28] ERROR [http-nio-8080-exec-5] UserDAOImpl.list(44) | org.hibernate.hql.internal.ast.QuerySyntaxException: Users is not mapped [from Users]
[2016-09-04 20:42:23] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 20:42:23] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@5bf6d{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 20:42:45] ERROR [http-nio-8080-exec-5] UserDAOImpl.insert(59) | Unknown entity: com.hiber.model.User
[2016-09-04 20:42:45] INFO [http-nio-8080-exec-5] UserController.addNew(60) | add new user -----> com.hiber.model.User@1d55ca7e
[2016-09-04 20:46:40] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 20:46:40] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@180a3c00{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 20:47:07] ERROR [http-nio-8080-exec-4] UserDAOImpl.insert(59) | no transaction is in progress
[2016-09-04 20:47:07] INFO [http-nio-8080-exec-4] UserController.addNew(60) | add new user -----> com.hiber.model.User@1f78e231
[2016-09-04 20:51:27] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 20:51:27] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@2c43b010{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 21:03:42] ERROR [http-nio-8080-exec-4] UserDAOImpl.insert(59) | no transaction is in progress
[2016-09-04 21:03:42] INFO [http-nio-8080-exec-4] UserController.addNew(60) | add new user -----> com.hiber.model.User@2b249d93
[2016-09-04 21:03:55] ERROR [http-nio-8080-exec-6] UserDAOImpl.insert(59) | no transaction is in progress
[2016-09-04 21:03:55] INFO [http-nio-8080-exec-6] UserController.addNew(60) | add new user -----> com.hiber.model.User@4a843a33
[2016-09-04 21:08:57] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 21:08:57] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@2347f6c{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 21:15:44] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 21:15:44] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@283adc5{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 21:17:32] INFO [http-nio-8080-exec-5] UserDAOImpl.list(37) | 0
[2016-09-04 21:17:39] ERROR [http-nio-8080-exec-6] UserDAOImpl.insert(60) | no transaction is in progress
[2016-09-04 21:17:39] INFO [http-nio-8080-exec-6] UserController.addNew(60) | add new user -----> com.hiber.model.User@37a5c0c0
[2016-09-04 21:17:39] INFO [http-nio-8080-exec-7] UserDAOImpl.list(37) | 0
[2016-09-04 21:17:54] INFO [http-nio-8080-exec-9] UserDAOImpl.list(37) | 0
[2016-09-04 21:20:53] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 21:20:53] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@5d36b174{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 21:24:07] ERROR [http-nio-8080-exec-7] UserDAOImpl.get(72) | org.hibernate.exception.SQLGrammarException: could not prepare statement
[2016-09-04 21:24:49] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 21:24:49] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@2e760a02{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 21:27:04] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 21:27:04] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@4a89a0a2{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 21:32:55] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 21:32:55] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@53343596{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 21:35:53] ERROR [http-nio-8080-exec-6] UserDAOImpl.insert(61) | no transaction is in progress
[2016-09-04 21:35:53] INFO [http-nio-8080-exec-6] UserController.addNew(60) | add new user -----> com.hiber.model.User@5aee4088
[2016-09-04 22:00:44] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 22:00:44] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@699108c4{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 22:03:12] ERROR [http-nio-8080-exec-6] UserDAOImpl.insert(61) | no transaction is in progress
[2016-09-04 22:03:12] INFO [http-nio-8080-exec-6] UserController.addNew(60) | add new user -----> com.hiber.model.User@4f4fcb8b
[2016-09-04 22:05:06] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 22:05:06] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@7b022de5{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 22:05:41] ERROR [http-nio-8080-exec-4] UserDAOImpl.insert(61) | no transaction is in progress
[2016-09-04 22:05:41] INFO [http-nio-8080-exec-4] UserController.addNew(60) | add new user -----> com.hiber.model.User@7ba61373
[2016-09-04 22:06:17] ERROR [http-nio-8080-exec-8] GroupDAOImpl.update(87) | no transaction is in progress
[2016-09-04 22:06:17] INFO [http-nio-8080-exec-8] GroupController.addNew(47) | save group -----> com.hiber.model.Group@352d3de3
[2016-09-04 22:06:49] ERROR [http-nio-8080-exec-9] GroupDAOImpl.update(87) | no transaction is in progress
[2016-09-04 22:06:49] INFO [http-nio-8080-exec-9] GroupController.addNew(47) | save group -----> com.hiber.model.Group@3a4ec75a
[2016-09-04 22:09:43] ERROR [main] ContextStartEventHandler.onApplicationEvent(44) | Context start: Table/View 'USERS' already exists in Schema 'SA'.
[2016-09-04 22:09:43] INFO [main] ContextStartEventHandler.onApplicationEvent(46) | Context start application org.apache.tomcat.jdbc.pool.DataSource@2bd4b1a0{ConnectionPool[defaultAutoCommit=null; defaultReadOnly=null; defaultTransactionIsolation=-1; defaultCatalog=null; driverClassName=org.apache.derby.jdbc.EmbeddedDriver; maxActive=100; maxIdle=100; minIdle=10; initialSize=10; maxWait=30000; testOnBorrow=true; testOnReturn=false; timeBetweenEvictionRunsMillis=5000; numTestsPerEvictionRun=0; minEvictableIdleTimeMillis=60000; testWhileIdle=false; testOnConnect=false; password=********; url=jdbc:derby:C:/Java/hiberdb; username=sa; validationQuery=SELECT 1 FROM SYSIBM.SYSDUMMY1; validationQueryTimeout=-1; validatorClassName=null; validationInterval=30000; accessToUnderlyingConnectionAllowed=true; removeAbandoned=false; removeAbandonedTimeout=60; logAbandoned=false; connectionProperties=null; initSQL=null; jdbcInterceptors=null; jmxEnabled=true; fairQueue=true; useEquals=true; abandonWhenPercentageFull=0; maxAge=0; useLock=false; dataSource=null; dataSourceJNDI=null; suspectTimeout=0; alternateUsernameAllowed=false; commitOnReturn=false; rollbackOnReturn=false; useDisposableConnectionFacade=true; logValidationErrors=false; propagateInterruptState=false; ignoreExceptionOnPreLoad=false; }
[2016-09-04 22:10:35] ERROR [http-nio-8080-exec-4] UserDAOImpl.insert(63) | no transaction is in progress
[2016-09-04 22:10:35] INFO [http-nio-8080-exec-4] UserController.addNew(60) | add new user -----> com.hiber.model.User@7ba61373
